import { type AppType } from 'next/app'
import { trpc } from '../utils/trpc'
import Head from 'next/head'
import '../components/Calendar.css'
import '../styles/globals.css'
import '../styles/Spinner.css'

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Flywat3r Swim-Gym</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default trpc.withTRPC(MyApp)
